const ExcelJS = require('exceljs');
const PDFDocument = require('pdfkit-table');
const moment = require('moment');
const path = require('path');

async function writeRiwayatExcel(res, rows) {
    const workbook = new ExcelJS.Workbook();
    const sheet = workbook.addWorksheet('Riwayat Absensi');

    sheet.columns = [
        { header:'Tanggal', key:'tanggal', width:15 },
        { header:'NIK', key:'nik', width:10 },
        { header:'Nama', key:'nama', width:28 },
        { header:'Jabatan', key:'jabatan', width:25 },
        { header:'Jam Masuk', key:'jam_masuk', width:15 },
        { header:'Jam Keluar', key:'jam_keluar', width:15 },
        { header:'Keterangan Masuk', key:'keterangan_masuk', width:35 },
        { header:'Keterangan Keluar', key:'keterangan_keluar', width:35 }
    ];

    rows.forEach(row => {
        sheet.addRow({
            tanggal: moment(row.tanggal).format('DD-MM-YYYY'),
            nik: row.nik,
            nama: row.nama,
            jabatan: row.jabatan,
            jam_masuk: row.jam_masuk || '-',
            jam_keluar: row.jam_keluar || '-',
            keterangan_masuk: row.keterangan_masuk || '-',
            keterangan_keluar: row.keterangan_keluar || '-'
        });
    });

    sheet.getRow(1).font = { bold:true };

    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    res.setHeader('Content-Disposition', 'attachment; filename=riwayat_absensi.xlsx');

    await workbook.xlsx.write(res);
    res.end();
}

async function writeRiwayatPdf(res, rows, query = {}) {
    const doc = new PDFDocument({
        size: 'A4',
        margin: 40,
        bufferPages: true
    });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'inline; filename="riwayat_absensi.pdf"');

    doc.pipe(res);

    const logoPath = path.join(__dirname, '../public/images/fotopabrik.JPG');

    try {
        doc.image(logoPath, 190, 70, { width: 220 });
    } catch (error) {
        doc.fontSize(12).text('Logo tidak ditemukan', { align: 'center' });
    }

    doc.moveDown(12);
    doc.fontSize(22).font('Helvetica-Bold').fillColor('black').text('PT TWINK INDONESIA', { align: 'center' });
    doc.moveDown(1);
    doc.fontSize(20).font('Helvetica-Bold').text('LAPORAN RIWAYAT ABSENSI', { align: 'center' });
    doc.moveDown(1);
    doc.fontSize(14).font('Helvetica').text('Periode : ' + (query.bulan || 'Semua Data'), { align: 'center' });
    doc.moveDown(8);
    doc.fontSize(12).fillColor('gray').text('Generated by Sistem Informasi Absensi', { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(11).text('PT Twink Indonesia', { align: 'center' });

    doc.addPage();
    doc.fontSize(16).font('Helvetica-Bold').fillColor('black').text('LAPORAN RIWAYAT ABSENSI', { align: 'center' });
    doc.moveDown(1);

    if (!rows.length) {
        doc.fontSize(12).text('Tidak ada data absensi.', { align: 'center' });
    } else {
        const table = {
            headers: [
                { label: 'No', property: 'no', width: 35 },
                { label: 'Tanggal', property: 'tanggal', width: 75 },
                { label: 'NIK', property: 'nik', width: 55 },
                { label: 'Nama', property: 'nama', width: 135 },
                { label: 'Jabatan', property: 'jabatan', width: 105 },
                { label: 'Masuk', property: 'masuk', width: 60 },
                { label: 'Keluar', property: 'keluar', width: 60 }
            ],
            datas: rows.map((row, index) => ({
                no: index + 1,
                tanggal: row.tanggal ? moment(row.tanggal).format('DD-MM-YYYY') : '-',
                nik: row.nik || '-',
                nama: row.nama || '-',
                jabatan: row.jabatan || '-',
                masuk: row.jam_masuk || '-',
                keluar: row.jam_keluar || '-'
            }))
        };

        await doc.table(table, {
            prepareHeader: () => doc.font('Helvetica-Bold').fontSize(9),
            prepareRow: () => doc.font('Helvetica').fontSize(8)
        });
    }

    const range = doc.bufferedPageRange();
    for (let i = range.start; i < range.start + range.count; i++) {
        doc.switchToPage(i);
        doc.fontSize(9).fillColor('gray').text(`Halaman ${i + 1} dari ${range.count}`, 40, 800, { align: 'center' });
    }

    doc.end();
}

module.exports = {
    writeRiwayatExcel,
    writeRiwayatPdf
};
